from datetime import datetime, timedelta, time


DAYTIME_SCHEDULE_START_TIME = time(8, 00)
NIGHTTIME_SCHEDULE_START_TIME = time(20, 00)

RELAY_BOARD_COM_STRING = "/dev/ttyUSB0"
RELAY_BOARD_BAUD = 9600

MIX_RUN_TIME_SECS = 30
VALVE_EXERCISE_TIME_SECS = 5

PH_LOW_LEVEL = 5.4
PH_HIGH_LEVEL = 6.1
PH_ADJUST_DOSE_RUN_TIME_SECS = 5
