from datetime import datetime, timedelta, time


DAYTIME_SCHEDULE_START_TIME = "09:06"
NIGHTTIME_SCHEDULE_START_TIME = "22:43"

RELAY_BOARD_ID = "HW554"

MIX_RUN_TIME_SECS = 30
VALVE_EXERCISE_TIME_SECS = 5

PH_LOW_LEVEL = 5.4
PH_HIGH_LEVEL = 6.1
PH_ADJUST_DOSE_RUN_TIME_SECS = 5
